# Generated by Django 3.2.7 on 2021-09-22 10:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date_publication', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('date_publication', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('finished', 'Завершена'), ('writing', 'Продолжается')], max_length=20)),
                ('genre', models.CharField(choices=[('rumanga', 'Руманга')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookinstances', to='core.book')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bookinstance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.bookinstance')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstanceExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bookinstances/covers/')),
                ('image_preview_1', models.ImageField(upload_to='bookinstances/previews/')),
                ('image_preview_2', models.ImageField(upload_to='bookinstances/previews/')),
                ('bookinstance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookinstance_extra', to='core.bookinstance')),
            ],
        ),
    ]
