# Generated by Django 3.2.7 on 2021-09-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookinstanceextra',
            name='image_preview_1',
            field=models.ImageField(blank=True, null=True, upload_to='bookinstances/previews/'),
        ),
        migrations.AlterField(
            model_name='bookinstanceextra',
            name='image_preview_2',
            field=models.ImageField(blank=True, null=True, upload_to='bookinstances/previews/'),
        ),
    ]
